language: python
python:
    - "3.7"
virtualenv:
    system_site_packages: true
install:
    - pip install -r requirements.txt
    - pip install -e .
    - python setup.py -q install
script:
    - nosetests